---
title: tweak
actions:
  - !writeStatus: {status: 'Disabling energy logging'}

  - !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\TaggedEnergy'
    value: 'DisableTaggedEnergyLogging'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\TaggedEnergy'
    value: 'TelemetryMaxApplication'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\EnergyEstimation\TaggedEnergy'
    value: 'TelemetryMaxTagPerApplication'
    data: '0'
    type: REG_DWORD