---
title: tweak
actions:
  - !writeStatus: {status: 'Disabling automatic maintenance'}

  - !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Schedule\Maintenance'
    value: 'MaintenanceDisabled'
    data: '1'
    type: REG_DWORD