---
title: tweak
actions:
- !writeStatus: {status: 'Optimizing disk'}

- !cmd: {command: 'fsutil behavior set memoryusage 2 >nul 2>&1'}
- !cmd: {command: 'fsutil behavior set mftzone 4 >nul 2>&1'}
- !cmd: {command: 'fsutil behavior set disablelastaccess 1 >nul 2>&1'}
- !cmd: {command: 'fsutil behavior set disabledeletenotify 0 >nul 2>&1'}
- !cmd: {command: 'fsutil behavior set encryptpagingfile 0 >nul 2>&1'}
