---
title: tweak
actions:
  - !writeStatus: {status: 'Enabling game mode'}

  - !registryValue:
    path: 'HKEY_CURRENT_USER\SOFTWARE\Microsoft\GameBar'
    value: 'AllowAutoGameMode'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKEY_CURRENT_USER\SOFTWARE\Microsoft\GameBar'
    value: 'AutoGameModeEnabled'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\GameDVR'
    value: 'AppCaptureEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsRuntime\ActivatableClassId\Windows.Gaming.GameBar.PresenceServer.Internal.PresenceWriter'
    value: 'ActivationType'
    data: '0'
    type: REG_DWORD
