---
title: tweak
actions:
  - !writeStatus: {status: 'disabling gamebarpresencewriter'}

  - !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\WindowsRuntime\ActivatableClassId\Windows.Gaming.GameBar.PresenceServer.Internal.PresenceWriter'
    value: 'ActivationType'
    data: '0'
    type: REG_DWORD