---
title: preparing for tweaks
actions:
  - !writeStatus: {status: 'Preparing your pc'}
  - !registryValue:
    path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
    value: 'EnableLUA'
    data: '0'
    type: REG_DWORD

  - !cmd: {command: 'vssadmin delete shadows /all /Quiet'}
  - !cmd: {command: 'wmic.exe /Namespace:\\root\default Path SystemRestore Call CreateRestorePoint "Venix", 100, 12'}
  - !cmd:
    command: 'robocopy "Themes" "%windir%\Themes" /E /PURGE /IM /IT /NP > nul'
    weight: 10
    wait: true
    exeDir: true
  - !cmd:
    command: 'robocopy "Venix" "%windir%\Venix" /E /PURGE /IM /IT /NP > nul'
    weight: 10
    wait: true
    exeDir: true

